const js = require('@eslint/js');
const ts = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');

module.exports = [
    js.configs.recommended,
    {
        files: ['**/*.ts', '**/*.tsx'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 2020,
                sourceType: 'module',
            },
            globals: {
                console: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                module: 'readonly',
                require: 'readonly',
                exports: 'writable',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                RequestInit: 'readonly',
                Response: 'readonly',
                URL: 'readonly',
                atob: 'readonly',
                btoa: 'readonly',
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                location: 'readonly',
                history: 'readonly',
                MutationObserver: 'readonly',
                ResizeObserver: 'readonly',
                IntersectionObserver: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLSpanElement: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                MessageEvent: 'readonly',
                ErrorEvent: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                chrome: 'readonly',
                browser: 'readonly',
                indexedDB: 'readonly',
                IDBDatabase: 'readonly',
                IDBObjectStore: 'readonly',
                IDBIndex: 'readonly',
                IDBTransaction: 'readonly',
                IDBKeyRange: 'readonly',
                IDBCursor: 'readonly',
                BroadcastChannel: 'readonly',
                Worker: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                Headers: 'readonly',
                Request: 'readonly',
                AbortController: 'readonly',
                AbortSignal: 'readonly',
                ReadableStream: 'readonly',
                WritableStream: 'readonly',
                TransformStream: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                Image: 'readonly',
                Audio: 'readonly',
                Canvas: 'readonly',
                WebSocket: 'readonly',
                XMLHttpRequest: 'readonly',
                EventSource: 'readonly',
                crypto: 'readonly',
                CryptoKey: 'readonly',
                SubtleCrypto: 'readonly',
                acquireVsCodeApi: 'readonly',
            },
        },
        plugins: {
            '@typescript-eslint': ts,
        },
        rules: {
            ...ts.configs.recommended.rules,
            '@typescript-eslint/no-unused-vars': ['error', { 
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                destructuredArrayIgnorePattern: '^_'
            }],
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-require-imports': 'off',
            '@typescript-eslint/no-unsafe-function-type': 'warn',
            'no-case-declarations': 'off',
        },
    },
    {
        ignores: ['dist/**', 'node_modules/**', '*.d.ts', '**/stubs/*.js', '**/webview/scripts/*.js'],
    },
];
